const fname = 'Ahmed';
const lname = 'Satti';
const age = 35;
const dob = '01-01-1990';
const address = 'calgary, AB';
console.log('first name: ', fname);
console.log('last name: ', lname);
console.log('age: ', age);
console.log('date of birth: ', dob);
console.log('address: ', address);