var fname = 'Ahmed';
var lname = 'Satti';
var age = 35;
var dob = '01-01-1990';
var address = 'calgary, AB';
console.log(fname);
console.log(lname);
console.loga(age);
console.log(dob);
console.log(address);