let fname = 'Ahmed';
let lname = 'Satti';
let age = 35;
let dob = '01-01-1990';
let address = 'calgary, AB';
console.log('first name: ', fname);
console.log('last name: ', lname);
console.log('age: ', age);
console.log('date of birth: ', dob);
console.log('address: ', address);