var fname = 'Ahmed';
var lname = 'Satti';
var age = 35;
var dob = '01-01-1990';
var address = 'calgary, AB';
console.log('first name: ', fname);
console.log('last name: ', lname);
console.loga('age: ', age);
console.log('date of birth: ', dob);
console.log('address: ', address);